version: "2"
checks:
  file-lines:
    config:
      threshold: 300
  method-complexity:
    config:
      threshold: 15
  method-count:
    config:
      threshold: 40
  method-lines:
    config:
      threshold: 50
