FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.9

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src

RUN pip3 install \
      python-coveralls \
      coverage \
      nose \
      future \
      flake8 \
      black \
      pre-commit

WORKDIR /workspaces

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash
